# Generated by Django 4.0.4 on 2022-05-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='1233', unique=True),
            preserve_default=False,
        ),
    ]
