# Generated by Django 4.0.4 on 2022-05-28 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_views_count_user_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
