# Generated by Django 4.0.4 on 2022-05-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='day_visited_in_a_row',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
