# Generated by Django 4.0.4 on 2022-05-28 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_day_visited_in_a_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
