# Generated by Django 4.0.4 on 2022-05-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_day_visited_in_a_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
