# Generated by Django 4.0.4 on 2022-05-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_advert_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
