# Generated by Django 4.0.4 on 2022-05-29 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_advert_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
