# Generated by Django 4.0.4 on 2022-05-28 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_post_alter_user_coin_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
