# Generated by Django 4.0.4 on 2022-05-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_last_visit_user_last_time_gained_pulse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='day_visited_in_a_row',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
