# Generated by Django 4.0.4 on 2022-05-29 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from api.models import User


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_grade_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='owner',
            field=models.ForeignKey(default=User.objects.last().id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(default='https://imagur.com/'),
            preserve_default=False,
        ),
    ]
