# Generated by Django 4.0.4 on 2022-05-29 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='owner',
            new_name='seller',
        ),
        migrations.AddField(
            model_name='lot',
            name='amount_coins',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=30, verbose_name='Монет'),
        ),
        migrations.AddField(
            model_name='lot',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lot',
            name='closed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lot',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lot',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='is_committed',
            field=models.BooleanField(default=False),
        ),
    ]
