version: '3'

services:
  web:
    build:
      context: ./django
      dockerfile: Dockerfile.prod
    command: gunicorn BotWeb.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  authbot:
    command: python manage.py authbot
    build: ./django
    depends_on:
      - db
      - web
    env_file:
      - ./.env.prod

volumes:
  postgres_data:
  static_volume:
